# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_upload',
            name='musician_address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user_upload',
            name='musician_contactNumber',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user_upload',
            name='musician_email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user_upload',
            name='musician_genre',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user_upload',
            name='musician_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user_upload',
            name='musician_priceRate',
            field=models.CharField(max_length=250),
        ),
    ]
